// Authored narration. Product actions must be backed by final real captures before rendering.
const scene = (
  id,
  seconds,
  title,
  eyebrow,
  captureKey,
  frame,
  narration,
  extra = {},
) => ({ id, seconds, title, eyebrow, captureKey, frame, narration, ...extra });
export const videos = {
  proof: {
    title: "DUIT · Make the next meeting count",
    privacy: "Private review · narrated render proof",
    scenes: [
      scene(
        "proof-intro",
        10,
        "Make the next\nmeeting count.",
        "DUIT / 2026 PRIVATE PILOT",
        "proof-public-profile",
        "phone",
        "Share what you do. Remember who you met. DUIT helps the conversation survive the journey home.",
        {
          subtitle: "Share what you do.\nRemember what matters.",
          capture: "artifacts/qa/shared-profile-phone-initial.png",
          captureLabel: "Actual shared profile · initial QA capture",
          crop: "top",
          audio: "artifacts/videos/audio/proof-intro.mp3",
          audioTranscript:
            "Share what you do. Remember who you met. Do-it helps the conversation survive the journey home.",
          voiceProvider: "AI Voice Generator",
          voiceId: "clear",
          audioLead: 0.8,
        },
      ),
    ],
  },
  main: {
    title: "DUIT 2026 · From hello to a useful next step",
    privacy: "Private review · fictional pilot + private historical archive",
    scenes: [
      scene(
        "main-01",
        25,
        "The card is\njust the start.",
        "01 / A BETTER HELLO",
        "maya-today",
        "phone",
        "You meet someone interesting. You swap details. Then life happens, and the card joins a very impressive collection of people you almost remember. DUIT starts with a simple idea: share what you do, remember the conversation, and keep the next step close. This is the working private pilot. The modern people and businesses in this demo are fictional.",
        { subtitle: "Share. Remember. Follow through." },
      ),
      scene(
        "main-02",
        29,
        "A business profile.\nWith a point.",
        "02 / WHAT MAYA DOES",
        "maya-card-review",
        "phone",
        "Meet Maya, founder of Northstar Studio. Her profile explains who she helps, what she offers, and what a sensible first step looks like. Six short panels tell the story. Maya can edit and review each one before publishing. This is a business introduction, not her entire career history. The useful question is: can she help with what I need right now?",
        { subtitle: "A clear offer. A clear next step." },
      ),
      scene(
        "main-03",
        28,
        "Open the link.\nGet the idea.",
        "03 / NO APP REQUIRED",
        "public-profile",
        "phone",
        "The same profile opens in a normal phone browser. No app installation stands between you and the introduction. A link can be copied into WhatsApp or shown as a QR code. The recipient can read the offer, move through the pitch, or save the contact. Sharing opens the chosen service; DUIT does not pretend that opening WhatsApp means somebody received or read the message.",
        { subtitle: "Useful before sign-up." },
      ),
      scene(
        "main-04",
        24,
        "A useful reply.\nNot another like.",
        "04 / EXPRESS INTEREST",
        "public-enquiry",
        "phone",
        "Here is the important button: tell Maya what you are building. The visitor leaves a short, consented enquiry, and Maya sees it in her workspace. A profile view is one thing. A specific problem and a request to talk are another. We keep those counts separate. This enquiry is demo activity, so it does not become a claim about real customers.",
        { subtitle: "Give the next conversation a starting point." },
      ),
      scene(
        "main-05",
        31,
        "Their details.\nTheir decision.",
        "05 / RECIPIENT CLAIM",
        "recipient-claim",
        "desktop",
        "A sender can prepare a private starting draft for the person they met. That can save typing, but it does not make the details correct, or prove who owns the address. The recipient still verifies and reviews the draft before accepting it. In this local pilot, verification messages go to a private test inbox. That is not live email delivery. A forwarded link alone cannot take over somebody else’s identity.",
        { subtitle: "A starting draft is not a verified identity." },
      ),
      scene(
        "main-06",
        27,
        "Find the person.\nKeep the context.",
        "06 / PEOPLE",
        "people-filters",
        "phone",
        "Back in Maya’s network, people have more than a name and a number. We can see their business, where they are based, and how the relationship is progressing. Filters narrow the list by place or relationship. Events bring an evening’s conversations together. That means the person from the Singapore evening does not disappear into a thousand-name scroll. Names are useful. A little context is usually what makes them useful again.",
        { subtitle: "People, events and useful details." },
      ),
      scene(
        "main-07",
        28,
        "Paris was busy.\nThis is the useful part.",
        "07 / THE EVENT VIEW",
        "paris-event",
        "phone",
        "Open the Paris event and the conversations come back together. Who did Maya meet? Which business did each person represent? What did they talk about? The event and location belong to the saved encounter. They are not proof of a purchase, or a secret background location trail. These events and venues are fictional, and the map pins are approximate city locations.",
        { subtitle: "Who. Where. What next." },
      ),
      scene(
        "main-08",
        30,
        "One person.\nMore than one meeting.",
        "08 / RELATIONSHIP MEMORY",
        "noah-encounters",
        "phone",
        "Here is Noah from Fieldwork. Maya did not meet him just once. The first conversation was about event follow-up. Later they compared a small pilot, then clarified who would review the sample. Each encounter keeps its own date and note. That is the difference between a contact list and a useful memory. We can pick up the conversation without starting every call with: remind me what you do again?",
        { subtitle: "The next hello can start where the last one ended." },
      ),
      scene(
        "main-09",
        30,
        "Save the thought\nbefore it escapes.",
        "09 / CAPTURE",
        "save-meeting",
        "phone",
        "After a conversation, Maya records what matters: the person, event, date, short note and any promise. The original note stays attached. Here we save a concrete next step, then reopen it to check that it is really there. No automatic message goes out. A good meeting note does not need to be an essay. It needs enough detail for future you, who has already forgotten where the coffee was.",
        { subtitle: "A short note. A named next step." },
      ),
      scene(
        "main-10",
        30,
        "I need this.\nYou offer that.",
        "10 / NEEDS AND OFFERS",
        "needs-evidence",
        "phone",
        "Maya wants a partner for private document AI. Sofia’s saved profile and meeting note explain that she builds review-first document workflows. That is a useful reason to reconnect. The current saved-evidence search shows the details behind a result. It is not mind reading, and it is not a guaranteed match. Needs and offers make the network easier to use, while the supporting note tells us why a suggestion might make sense.",
        { subtitle: "Show the reason, not a mysterious score." },
      ),
      scene(
        "main-11",
        24,
        "A promise kept\nis a better metric.",
        "11 / FOLLOW THROUGH",
        "complete-commitment",
        "phone",
        "Now the follow-up has an owner and a date. Maya can see what is due, open the person’s context, and mark the promise complete when she has actually done it. A reminder is not a reply. A reply is not a sale. The product should help people take the next useful step, then record what really happened.",
        { subtitle: "A clear owner. A real action." },
      ),
      scene(
        "main-12",
        32,
        "AI should help.\nYou stay in charge.",
        "12 / HONEST AI STATUS",
        "ai-status",
        "phone",
        "The AI tools are designed for small jobs: read a card, improve a draft, summarise an approved note, or help find a relevant person. Suggestions need review, and original images stay available. For this recording, the provider is not configured, so the screen says so. We are not playing a canned answer and calling it intelligence. Real provider tests, quality checks and a spending limit are the next gate.",
        {
          subtitle: "Unconfigured in this recording. No simulated results.",
          conditional:
            "Replace only after approved live AI execution and captured original/result review.",
          approvedAlternative:
            "Here is a real provider response to this uploaded sample. Compare it with the original: names, numbers and claims still need review. We can edit the suggestion before applying it. The source and cost are recorded. One good example does not prove every card will be read correctly; that is why a varied test set and spending limits matter.",
        },
      ),
      scene(
        "main-13",
        29,
        "Count the right things.",
        "13 / OPERATOR WORKSPACE",
        "admin-overview",
        "desktop",
        "The operator workspace shows users, profiles and recorded activity. Demo data, new pilot activity and the old archive have different meanings, so we do not roll them into one impressive-looking number. We can inspect the current scope before reading a chart. The archive is not an active customer base. Private relationship notes are not ordinary admin browsing data. Good numbers should help us make a decision, not win a screenshot competition.",
        { subtitle: "Fictional demo, new activity and history stay distinct." },
      ),
      scene(
        "main-14",
        30,
        "The original idea\nis still here.",
        "14 / PRIVATE ARCHIVE",
        "archive-founders",
        "desktop",
        "The private archive brings the old DUIT story into view. Here are Prakhar Goel’s profile and business card, and Amandeep Singh’s archived card. Dates and the old received, sent and meeting-event counts stay labelled as historical. They explain what was recorded then, not who is using the new app today. These details are included for your private review, and are not published as modern user profiles.",
        { subtitle: "Prakhar Goel + Amandeep Singh · historical records" },
      ),
      scene(
        "main-15",
        28,
        "Three hundred\npieces of history.",
        "15 / THE CURATED GALLERY",
        "archive-gallery",
        "desktop",
        "The curated gallery contains three hundred archived profiles, with portraits, visiting cards and business images where available. We can filter and inspect them without putting them on a public page. India, Indonesia and Malaysia are the largest phone-code groups in this selection. Phone codes are not proof of nationality or where somebody lives. And this is a selected gallery, not a claim about the size of the whole network.",
        { subtitle: "300 selected profiles · operator-private" },
      ),
      scene(
        "main-16",
        30,
        "Build a habit.\nThen build a business.",
        "16 / THE 2026 TEST",
        null,
        "title",
        "Digital cards and AI notes already exist. Our opportunity is to make the whole conversation-to-follow-up loop feel natural for a specific group of people. Start with twenty to thirty founders or small business teams, across two real events. Watch whether they publish a useful profile, save the context, follow up, and return after the event. Ask what helped, what felt like work, and what they would miss.",
        {
          subtitle: "20–30 people. Two events. One useful loop.",
          points: [
            "A useful introduction",
            "A remembered conversation",
            "A next step completed",
          ],
          sources: [
            "https://blinq.me/pricing",
            "https://support.blinq.me/en/articles/71264-ai-notetaker-the-basics",
            "https://www.hihello.com/features/digital-business-cards",
            "https://popl.co/pages/event-lead-capture",
          ],
        },
      ),
      scene(
        "main-17",
        28,
        "Make the next\nmeeting count.",
        "17 / WHAT WE PROVE NEXT",
        null,
        "title",
        "Then test willingness to pay with people who have used it. A free useful profile and a paid ongoing workflow are pricing ideas to test, not a revenue forecast. The first milestone is smaller and harder than becoming a giant network: help somebody remember the right person, make a useful introduction, and keep a promise. Do that often enough, and we have something worth growing.",
        {
          subtitle: "Useful conversations first. Growth follows evidence.",
          points: [
            "Return after the event",
            "Follow through more often",
            "Earn the right to charge",
          ],
        },
      ),
    ],
  },
  quick: {
    title: "DUIT 2026 · The useful next step",
    privacy: "Private review · fictional demo",
    scenes: [
      scene(
        "quick-01",
        10,
        "Make the next\nmeeting count.",
        "DUIT / 2026",
        "maya-today",
        "phone",
        "A business card should start a useful conversation. DUIT helps you share what you do, remember who you met, and know what comes next.",
        { subtitle: "Share. Remember. Follow through." },
      ),
      scene(
        "quick-02",
        12,
        "A profile people\ncan act on.",
        "01 / SHARE",
        "public-profile",
        "phone",
        "Maya’s business profile opens in the browser. No app needed. A clear offer, a short pitch, and a button that gives the next conversation a starting point.",
        { subtitle: "Useful before sign-up." },
      ),
      scene(
        "quick-03",
        12,
        "Keep the meeting\nwith the person.",
        "02 / REMEMBER",
        "paris-event",
        "phone",
        "Back from the Paris event, Maya can find the people she met, the notes she saved, and the promises she made. The memory comes with the name.",
        { subtitle: "Who. Where. What next." },
      ),
      scene(
        "quick-04",
        12,
        "Not just names.\nUseful reasons.",
        "03 / CONNECT",
        "needs-evidence",
        "phone",
        "She needs a private document AI partner. Sofia offers exactly that kind of work. Saved details explain why this is worth a conversation. No mysterious compatibility score required.",
        { subtitle: "Needs + offers + saved evidence." },
      ),
      scene(
        "quick-05",
        11,
        "Keep the promise\nwithin reach.",
        "04 / FOLLOW THROUGH",
        "complete-commitment",
        "phone",
        "Add a next step and a date. Then mark it complete when it is done. A full contact list is nice. A useful follow-up is better.",
        { subtitle: "Turn good intentions into a small action." },
      ),
      scene(
        "quick-06",
        12,
        "Be clear about\nwhat is real.",
        "05 / THE PRIVATE PILOT",
        "ai-status",
        "phone",
        "These modern profiles are fictional demo data. AI is not configured in this recording; suggestions are never disguised as live results. The old archive stays private and clearly historical.",
        {
          subtitle: "Fictional demo. Private archive. Honest AI status.",
          conditional:
            "Revise AI clause only after a real approved provider result is recorded.",
        },
      ),
      scene(
        "quick-07",
        11,
        "The story\nkeeps its roots.",
        "06 / HISTORY",
        "archive-founders",
        "desktop",
        "The operator can explore three hundred selected archived profiles, including Prakhar and Amandeep. Their old cards remain history, not inflated modern growth numbers.",
        { subtitle: "300 selected historical profiles · private review" },
      ),
      scene(
        "quick-08",
        10,
        "A better next hello.",
        "DUIT / MAKE THE NEXT MEETING COUNT",
        null,
        "title",
        "The next test is simple: do people follow through, come back, and find it useful enough to pay for? That is how we earn the next chapter.",
        { subtitle: "The conversation is where the value begins." },
      ),
    ],
  },
};
// 7m45s editorial target; the renderer extends a scene rather than cutting speech.
for (const id of [
  "main-02",
  "main-05",
  "main-07",
  "main-08",
  "main-09",
  "main-10",
  "main-12",
  "main-14",
  "main-15",
])
  videos.main.scenes.find((scene) => scene.id === id).seconds -= 2;
export const captureRequests = [
  [
    "maya-today",
    "Android",
    "Maya Today; briefly scroll due items. Start signed in, never record credentials.",
  ],
  [
    "maya-card-review",
    "Android",
    "Open My card, edit text, review the six owner-authored panels. Show actual publish only if approved fixture edit is intended.",
  ],
  [
    "public-profile",
    "Phone browser",
    "Signed out Maya card; navigate panels and save contact. Show real page; avoid full-page stitched screenshot.",
  ],
  [
    "public-enquiry",
    "Phone browser",
    "Fill a fictional .test enquiry, consent and submit; show success and owner lead later. No real messages.",
  ],
  [
    "recipient-claim",
    "Desktop browser",
    "Show private draft claim/review. Verification uses local outbox. Hide token, code, verification URL and credentials from recording.",
  ],
  [
    "people-filters",
    "Android",
    "People; country/relationship filter; choose a relevant contact; clear filter. Events are grouped under Meetings.",
  ],
  [
    "paris-event",
    "Android",
    "Paris AI Week (Demo), people, encounters and confirmed venue/city.",
  ],
  [
    "noah-encounters",
    "Android",
    "Noah detail; scroll dated encounter history and open one note.",
  ],
  [
    "save-meeting",
    "Android",
    "Save a short fictional note/next promise for an existing demo contact, then reopen it. Capture exact resulting text/date for narration.",
  ],
  [
    "needs-evidence",
    "Android",
    "Needs/offers and saved-evidence search for private document AI; open Sofia evidence. Do not call lexical search a live AI answer.",
  ],
  [
    "complete-commitment",
    "Android",
    "Open due item and mark complete after the demo action; show persisted status.",
  ],
  [
    "ai-status",
    "Android",
    "Actual provider-unconfigured/error status, or separately approved real result with source and review.",
  ],
  [
    "admin-overview",
    "Desktop browser",
    "Overview; select demo versus other activity scopes; show truthful numbers and AI status.",
  ],
  [
    "archive-founders",
    "Desktop browser",
    "Archive filter; Prakhar Goel detail, then Amandeep Singh detail. Name/card images are authorized only in private deliverables.",
  ],
  [
    "archive-gallery",
    "Desktop browser",
    "Country filter and gentle gallery scroll; view image labels/dates; show 300-profile selected archive context.",
  ],
].map(([key, surface, action]) => ({ key, surface, action }));
